apiVersion: v1
kind: Namespace
metadata:
  name: karpenter
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
  namespace: flux-system
spec:
  releaseName: karpenter
  targetNamespace: karpenter
  storageNamespace: karpenter
  interval: 1m0s
  chart:
    spec:
      chart: karpenter
      version: v0.27.3
      sourceRef:
        kind: HelmRepository
        name: karpenter
  values:
    serviceAccount:
      create: true
      name: karpenter # SA created via eksctl or
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::411644331275:role/eks-upgrade-demo-karpenter # Replace
    settings:
      aws:
        clusterName: eks-upgrade-demo
        clusterEndpoint: https://EE21E1FC609B7A4070F5540E88072088.gr7.eu-west-3.eks.amazonaws.com # Replace
        defaultInstanceProfile: KarpenterNodeInstanceProfile-eks-upgrade-demo # Replace
        interruptionQueueName: eks-upgrade-demo
  install: {}
 